<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<dl class="payment-method purchase order">
    <dt class="title"><?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <dd class="content">
        <strong><?php echo __('Name on Credit Card') ?></strong>
        <span class="number"><?php echo $block->escapeHtml($block->getInfo()->getCcName()) ?></span>
    </dd>
    <dd class="content">
        <strong><?php echo __('Credit Card Number') ?></strong>
        <span class="number"><?php echo $block->escapeHtml($block->getInfo()->getCcNumber()) ?></span>
    </dd>
    <dd class="content">
        <strong><?php echo __('Expiry') ?></strong>
        <span class="number"><?php echo $block->escapeHtml($block->getInfo()->getCcExp()) ?></span>
    </dd>
    <dd class="content">
        <strong><?php echo __('CVV') ?></strong>
        <span class="number"><?php echo $block->escapeHtml($block->getInfo()->getCcCvv()) ?></span>
    </dd>
</dl>
